version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:14.8

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .
  build:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints: 'b4:3c:8e:ca:1d:46:21:ee:c9:2a:35:5e:d9:d7:e6:b3'
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: ls -al
      - run: npm run build
      - run: ls -al
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - save_cache:
          paths:
            - dist
          key: dist

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - test
          filters:
            tags:
              only: /.*/
